version: "3"

services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    volumes:
      - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./api-doc/dist:/usr/share/nginx/html
    ports:
      - "80:80"
      - "443:443"

  ldap:
    container_name: ldap
    image: osixia/phpldapadmin
    expose: ["443"]

  jenkins:
    container_name: jenkins
    image: jenkins:alpine
    build:
      # context: .
      # dockerfile: ./jenkins/Dockerfile
    # volumes:
    #   - ./jenkins/jenkins_home/secrets/initialAdminPassword:/var/jenkins_home/secrets/initialAdminPassword
    # TODO : 기본 비밀번호 설정 연동
    expose: ["8080"]