version: '3.7'

services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - $ROOT_PATH/nginx/conf:/etc/nginx/conf.d
      - $ROOT_PATH/nginx/certbot/conf:/etc/letsencrypt
      - $ROOT_PATH/nginx/certbot/www:/var/www/certbot
      - $ROOT_PATH/nginx/api-doc/dist:/usr/share/nginx/html
    ports:
      - "80:80"
      - "443:443"
    networks:
      - nginx
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  jenkins:
    container_name: jenkins
    image: jenkins:alpine
    expose: ["8080"]
    networks:
      - nginx
  
networks:
  nginx:
    driver: bridge