version: "3"

services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    volumes:
      - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./api-doc/dist:/usr/share/nginx/html
    ports:
      - "80:80"
      - "443:443"

  ldap:
    container_name: ldap
    image: osixia/phpldapadmin
    expose: ["443"]