version: '3.7'

services:
  # nginx:
  #   container_name: nginx
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #     - "433:433"
  #   volumes:
  #     - $ROOT_PATH/nginx/conf:/etc/nginx/conf.d:ro
  #     - $ROOT_PATH/nginx/certbot/conf:/etc/letsencrypt
  #     - $ROOT_PATH/nginx/certbot/www:/var/www/certbot
  #     - $ROOT_PATH/nginx/api-doc/dist:/usr/share/nginx/html
  #   networks:
  #     - nginx

  # ldap:
  #   container_name: ldap
  #   image: osixia/phpldapadmin
  #   expose: ["80", "443"]
  #   networks:
  #     - nginx

  jenkins:
    container_name: jenkins
    image: jenkins:alpine
    ports :
      - "8080:8080"
    # expose: ["8080"]
    volumes:
      - $ROOT_PATH/jenkins/jenkins_home/:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      TZ: "Asia/Seoul"
    # networks:
    #   - nginx

  # grafana:
  #   container_name: grafana
  #   image: grafana/grafana:latest
  #   # volumes:
  #   # expose: ["3000"]
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - nginx

  # db:
  #   container_name: mysql
  #   image: mysql:${MYSQL_VERSION}
  #   restart: always
  #   volumes:
  #     - $ROOT_PATH/mysql/data:/var/lib/mysql
  #   environment:
  #     MYSQL_DATABASE: 'team_play'
  #     MYSQL_USER: 'player'
  #     MYSQL_PASSWORD: '1234'
  #     MYSQL_ROOT_PASSWORD: '1234'
  #   ports:
  #     - "3306:3306"

#   elasticsearch:
#     container_name: elasticsearch
#     image: docker.elastic.co/elasticsearch/elasticsearch:${ELK_VERSION}
#     volumes:
#       - $ROOT_PATH/elk/elasticsearch-conf/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
#       - $ROOT_PATH/elk/elasticsearch-data:/usr/share/elasticsearch/data
#       # - $ROOT_PATH/elk/elasticsearch-log:/var/log/elasticsearch
#     ports:
#       - "9200:9200"
#       - "9300:9300"
#     environment:
#       ES_JAVA_OPTS: "-Xmx256m -Xms256m"
#     networks:
#       - elk

#   logstash:
#     container_name: logstash
#     image: docker.elastic.co/logstash/logstash:${ELK_VERSION}
#     volumes:
#       - $ROOT_PATH/elk/logstash-conf/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
#       - $ROOT_PATH/elk/logstash-conf/pipeline:/usr/share/logstash/pipeline:ro
#     #   - $ROOT_PATH/elk/logstash-log:/var/log/logstash
#     ports:
#       - "5000:5000/tcp"
#       - "9600:9600"
#     environment:
#       LS_JAVA_OPTS: "-Xmx256m -Xms256m"
#     networks:
#       - elk
#     depends_on:
#       - elasticsearch

#   kibana:
#     container_name: kibana
#     image: docker.elastic.co/kibana/kibana:${ELK_VERSION}
#     volumes:
#       - $ROOT_PATH/elk/kibana-conf/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
#       # - $ROOT_PATH/elk/kibana-log:/var/log/kibana
#     ports:
#       - "5601:5601"
#     networks:
#       - elk
#     depends_on:
#       - elasticsearch

# networks:
#   elk:
#     driver: bridge
  # nginx:
  #   driver: bridge