version: '3.7'

services:
  cloud-config-server:
    build:
      context: .
    container_name: cloud-config-server
    environment:
      - VIRTUAL_HOST=config.DOMAIN
      - LETSENCRYPT_HOST=config.DOMAIN
      - LETSENCRYPT_EMAIL=osj4872@gmail.com
      - VIRTUAL_PORT=8888
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    name: nginx-proxy