version: '3'

services:
    nginx-proxy:
        container_name: nginx-proxy
        image: jwilder/nginx-proxy
        ports:
            - 80:80
            - 443:443
        restart: always
        volumes:
            - ./nginx/html/dist:/usr/share/nginx/html
            - nginx-proxy-volume:/etc/nginx/certs        
            - nginx-proxy-volume:/etc/nginx/vhost.d
            - /var/run/docker.sock:/tmp/docker.sock:ro
        labels:
            - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

    etsencrypt-nginx-proxy:
        container_name: leten-nginx-proxy
        image: jrcs/letsencrypt-nginx-proxy-companion
        restart: always
        depends_on:
            - nginx-proxy
        volumes:
            - ./nginx/html/dist:/usr/share/nginx/html
            - nginx-proxy-volume:/etc/nginx/certs
            - nginx-proxy-volume:/etc/nginx/vhost.d
            - /var/run/docker.sock:/var/run/docker.sock:ro

networks:
  default:
    external:
      name: nginx-proxy

volumes:
    nginx-proxy-volume: