version: '3.7'

services:
  nginx-proxy:
    container_name: nginx-proxy
    image: jwilder/nginx-proxy
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

  nginx-proxy-letsencrypt:
    container_name: nginx-proxy-letsencrypt
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    depends_on:
      - nginx-proxy
    volumes:
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/var/run/docker.sock:ro
  
  nginx:
    container_name: api-doc
    image: nginx:alpine
    volumes:
      - ./nginx/html:/usr/share/nginx/html
    environment:
      - VIRTUAL_HOST=api.osj4872.shop
      - LETSENCRYPT_HOST=api.osj4872.shop
      - LETSENCRYPT_EMAIL=osj4872@gmail.com
      - VIRTUAL_PORT=80

  jenkins:
    container_name: jenkins
    image: jenkins:alpine
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=ci.osj4872.shop
      - LETSENCRYPT_HOST=ci.osj4872.shop
      - LETSENCRYPT_EMAIL=osj4872@gmail.com
      - VIRTUAL_PORT=8080
    
  grafana:
    container_name: grafana
    image: grafana/grafana
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=monitor.osj4872.shop
      - LETSENCRYPT_HOST=monitor.osj4872.shop
      - LETSENCRYPT_EMAIL=osj4872@gmail.com
      - VIRTUAL_PORT=3000

volumes:
  html:
  certs:
  vhost: