version: '3'

services:
  jenkins:
    container_name: jenkins
    image: jenkins:alpine
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=ci.fonnie.shop
      - LETSENCRYPT_HOST=ci.fonnie.shop
      - LETSENCRYPT_EMAIL=osj4872@gmail.com
      - VIRTUAL_PORT=8080
        
networks:
  default:
    external:
      name: nginx-proxy